### ISSUE TITLE
<leader><leader>W seems not working

### ISSUE THREAD

**Issue by jchain** [joequery/Stupid-EasyMotion#4]
It acts as same as the lower case w

**Comment by joequery** [comment]
Could you come up with an example? I use w vs W quite a bit, and it seems to work fine for me.

**Comment by jchain** [comment]
Never mind. It is my fault to understand the role of W wrongly. I thought that 'W' would make the hint characters (red) appear at the front of the each words (on a whitespace). It may be a good idea to do so since currently the red hint chars cover the initial letters of underlying words, which makes it hard to remember what the underlying word is. Just a humble suggestion. Anyway, your plugin just scratches my itch. Thank you so much for this great work!
